// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avpblstlowrwtuwzjwyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2cGJsc3Rsb3dyd3R1d3pqd3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODc4MTksImV4cCI6MjA3MjU2MzgxOX0.xNV2agAsn3PJGaTThfO0FFxrNr8QZbdjdaL5mwsDov4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});